# Generated by Django 4.0.1 on 2022-01-31 22:07

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('passenger_seats_in_car', models.IntegerField(default=0)),
                ('license_plate_num', models.CharField(max_length=20)),
                ('vehicle_model', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(default='open', max_length=50)),
                ('destination', models.CharField(max_length=150)),
                ('arrival_time', models.TimeField()),
                ('shareable', models.BooleanField(default=False)),
                ('passengers_requested', models.IntegerField(default=1)),
                ('vehicle_type_requested', models.CharField(blank=True, max_length=150)),
                ('rider_owner_user_id', models.IntegerField()),
                ('rider_sharer_user_id', models.IntegerField(default=0)),
                ('driver_user_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RideShareUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(default='Rider Owner', max_length=150)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('user_type', models.CharField(default='Rider Owner', max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RiderUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(default='Rider Owner', max_length=150)),
                ('active_ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.ride')),
            ],
        ),
    ]
